#pragma once
//通讯模块错误
static const int ERROR_NETWORK_CONNECT_MISSED = 1000;
static const int ERROR_NETWORK_CONNECT_FAILED = 1001;
static const int ERROR_NETWORK_SHUTDOWN_FAILED = 1005;
//分配模块错误
static const int ERROR_ALLOCATE_SHUTDOWN_FAILED = 1002;
static const int ERROR_ALLOCATE_SHUTDOWN_TIMEOUT = 1003;
static const int ERROR_ALLOCATE_SHUTDOWN_ABANDONED = 1004;
static const int ERROR_ALLOCATE_STARTUP_FAILED = 1008;
//编码器相关
static const int ERROR_ENCODER_STARTUP_MISSPCI9014 = 1006;
static const int ERROR_ENCODER_STARTUP_FAILED = 1007;